# Generated by Django 4.0.6 on 2022-07-06 20:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('NOR', 'Normal'), ('FIR', 'Fire'), ('WAT', 'Water'), ('GRA', 'Grass'), ('ELE', 'Electric'), ('ICE', 'Ice'), ('FIG', 'Fighting'), ('POI', 'Poison'), ('GND', 'Ground'), ('FLY', 'Flying'), ('PSY', 'Psychic'), ('BUG', 'Bug'), ('RCK', 'Rock'), ('GHO', 'Ghost'), ('DRN', 'Dragon')], max_length=255)),
                ('generation', models.CharField(choices=[('GEN1', 'GENERATION 1'), ('GEN2', 'GENERATION 2'), ('GEN3', 'GENERATION 3'), ('GEN4', 'GENERATION 4')], max_length=255)),
            ],
        ),
    ]
