# Generated by Django 4.0.6 on 2022-07-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='generation',
            field=models.CharField(choices=[('Generation 1', 'GEN1'), ('Generation 2', 'GEN2'), ('Generation 3', 'GEN3'), ('Generation 4', 'GEN4')], max_length=255),
        ),
    ]
