# Generated by Django 4.0.6 on 2022-07-06 20:48

from django.db import migrations, models
import pokemons.models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_alter_pokemon_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pokemons.models.upload_pokemon_image),
        ),
    ]
